### ISSUE TITLE
PayPal/Venmo/3D Secure option gives an error

### ISSUE THREAD

**Issue by ritvij-saxena** [pikaju/flutter-braintree#45]
> D/****MAGNES DEBUGGING MESSAGE****( 8270): DeviceInfoRequest returned PayPal-Debug-Id: a8eaf752d0558
> E/flutter ( 8270): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(braintree_error, BraintreeBrowserSwitchActivity missing, incorrectly configured in AndroidManifest.xml or another app defines the same browser switch url as this app. See https://developers.braintreepayments.com/guides/client-sdk/android/v2#browser-switch for the correct configuration, null)
> E/flutter ( 8270): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
> E/flutter ( 8270): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
> E/flutter ( 8270): <asynchronous suspension>
> E/flutter ( 8270): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
> E/flutter ( 8270): #3      BraintreeDropIn.start (package:flutter_braintree/src/drop_in.dart:23:34)
> E/flutter ( 8270): #4      _CheckOutPageState.startPaymentInterface (package:ojaexpress_consumer_flutter/screens/checkoutpage.dart:935:58)
> E/flutter ( 8270): #5      _CheckOutPageState.build.<anonymous closure> (package:ojaexpress_consumer_flutter/screens/checkoutpage.dart:880:36)
> E/flutter ( 8270): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
> E/flutter ( 8270): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
> E/flutter ( 8270): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
> E/flutter ( 8270): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
> E/flutter ( 8270): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
> E/flutter ( 8270): #11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
> E/flutter ( 8270): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
> E/flutter ( 8270): #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
> E/flutter ( 8270): #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
> E/flutter ( 8270): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
> E/flutter ( 8270): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
> E/flutter ( 8270): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
> E/flutter ( 8270): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
> E/flutter ( 8270): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> E/flutter ( 8270): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
> E/flutter ( 8270): #21     _invoke1 (dart:ui/hooks.dart:267:10)
> E/flutter ( 8270): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
> E/flutter ( 8270): 
> D/EGL_emulation( 8270): eglMakeCurrent: 0xe46ffd60: ver 3 0 (tinfo 0xc31be060)

**Comment by nicolobozzato** [comment]
Maybe it's too late, but it happened to me today. And my problem was that I had another app that used the same application id here on my phone.

`<activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
    android:launchMode="singleTask">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="${applicationId}.braintree" />
    </intent-filter>
</activity>`

Once I uninstalled it, it worked. 
Maybe it could be or have been your same problem
